name: test-linux

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
  pull_request:


jobs:
  imager-file-heif:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        LIBHEIF_RELEASE:
          - release: "1.11.0"
          - release: "1.12.0"
          - release: "1.13.0"
          - release: "1.14.2"
          - release: "1.15.2"
          - release: "1.16.2"
          - release: "1.17.6"
          - release: "1.18.2"
          - release: "1.19.8"
          - release: "1.20.2"
          - release: "1.21.2"
    uses: ./.github/workflows/dotest.yml
    with:
      libheif_release: ${{ matrix.LIBHEIF_RELEASE.release }}
