name: test-linux

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
  pull_request:


jobs:
  imager-file-heif:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        LIBHEIF_RELEASE:
          - "1.9.0"
          - "1.9.1"
          - "1.11.0"
          - "1.12.0"
          - "1.13.0"
          - "1.14.2"
          - "1.15.2"
          - "1.16.2"
          - "1.17.6"
          - "1.18.2"
          - "1.19.8"
          - "1.20.2"
          - "1.21.2"
    steps:
      - name: install dependencies cached
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: build-essential libgif-dev libwebp-dev libde265-dev automake autoconf libtool m4 git yasm pkgconf libx265-dev libopenjp2-7-dev libjpeg-turbo8-dev libaom-dev libsvtav1-dev librav1e-dev libopenh264-dev libavcodec-dev libavutil-dev libpng-dev libjpeg-turbo8-dev liblocal-lib-perl jq
          version: 1.2
      - name: variables
        run: |
            export INSTALL_PATH="$(realpath local)"
            echo "INSTALL_PATH=$INSTALL_PATH" >>$GITHUB_ENV
            export PKG_CONFIG_PATH="$INSTALL_PATH/lib/pkgconfig"
            echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH" >>$GITHUB_ENV

      - name: cache libheif
        id: cache-libheif
        uses: actions/cache@v5
        with:
          path: local
          key: libheif-${{ matrix.LIBHEIF_RELEASE }}-v1

      - name: install libheif
        if: steps.cache-libheif.outputs.cache-hit != 'true'
        run: |
            wget https://github.com/strukturag/libheif/releases/download/v${{ matrix.LIBHEIF_RELEASE }}/libheif-${{ matrix.LIBHEIF_RELEASE }}.tar.gz
            tar xzf libheif-${{ matrix.LIBHEIF_RELEASE }}.tar.gz
            cd libheif-${{ matrix.LIBHEIF_RELEASE }}
            mkdir build
            cmake --install-prefix "$INSTALL_PATH" -B build && cd build && make && sudo make install

      - name: libheif environment
        run: |
            echo "$INSTALL_PATH/bin" >>$GITHUB_PATH
            echo "LD_LIBRARY_PATH=$INSTALL_PATH/lib" >>$GITHUB_ENV

      - name: libheif tools
        run: |
            heif-enc --list-encoders || true
            [ -x $INSTALL_PATH/bin/heif-dec ] && heif-dec --list-decoders || true

      - name: local-lib environment
        run: |
            perl -Mlocal::lib | grep -v '^PATH' >source.sh
            . source.sh
            for name in $(sed -e 's/=.*//' <source.sh) ; do
               echo "$name=${!name}" >>$GITHUB_ENV
            done
            echo "$PERL_LOCAL_LIB_ROOT/bin" >>$GITHUB_PATH

      - name: imager prep
        run: |
            echo IMAGER_RELEASE=$(curl -sS 'https://fastapi.metacpan.org/v1/release/Imager' | jq -r '.["version"]') >>$GITHUB_ENV
            echo PERL_VERSION=$(perl -e 'print $^V') >>$GITHUB_ENV

      - name: cache imager
        id: cache-imager
        uses: actions/cache@v5
        with:
          path: ${{ env.PERL_LOCAL_LIB_ROOT }}
          key: imager-${{ env.IMAGER_RELEASE }}-${{ env.PERL_VERSION }}-v1

      - name: install Imager
        if: steps.cache-imager.outputs.cache-hit != 'true'
        run: |
            cpan Imager
      - name: perl version
        run: |
            perl -v
            perl -V
      - name: checkout
        uses: actions/checkout@v6
        with:
            path: main
      - name: configure
        run: |
            cd main
            perl Makefile.PL
      - name: build
        run: |
            cd main
            make -j2
      - name: test
        run: |
            cd main
            make test
      - name: artifacts
        uses: actions/upload-artifact@v7
        with:
            name: logs-${{ matrix.LIBHEIF_RELEASE }}
            path: main/testout/
            retention-days: 7
