name: test-linux

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
  pull_request:


jobs:
  imager-file-heif:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        LIBHEIF_RELEASE:
          - "1.9.0"
          - "1.9.1"
          - "1.11.0"
          - "1.12.0"
          - "1.13.0"
          - "1.14.2"
          - "1.15.2"
          - "1.16.2"
          - "1.17.6"
          - "1.18.2"
          - "1.19.8"
          - "1.20.2"
          - "1.21.2"
    steps:
      - name: install dependencies
        run: |
            #sudo add-apt-repository -y ppa:strukturag/libde265
            sudo apt-get update ||:
            sudo apt-get -y install build-essential libgif-dev libwebp-dev libde265-dev automake autoconf libtool m4 git yasm pkgconf libx265-dev libopenjp2-7-dev libjpeg-turbo8-dev libaom-dev libsvtav1-dev librav1e-dev libopenh264-dev libavcodec-dev libavutil-dev libpng-dev libjpeg-turbo8-dev
            # missing in ubuntu-latest libkvazaar-dev
      - name: install libheif
        run: |
            wget https://github.com/strukturag/libheif/releases/download/v${{ matrix.LIBHEIF_RELEASE }}/libheif-${{ matrix.LIBHEIF_RELEASE }}.tar.gz
            ls
            tar xzf libheif-${{ matrix.LIBHEIF_RELEASE }}.tar.gz
            ls
            cd libheif-${{ matrix.LIBHEIF_RELEASE }}
            mkdir build
            cmake -B build && cd build && make && sudo make install
            echo "LD_LIBRARY_PATH=$(pkg-config --variable=libdir libheif)" >>$GITHUB_ENV
            examples/heif-enc --list-encoders || true
            [ -x examples/heif-dec ] && examples/heif-dec --list-decoders || true
      - name: install Imager
        run: |
            sudo cpan Imager
      - name: perl version
        run: |
          perl -v
          perl -V
      - name: checkout
        uses: actions/checkout@v6
      - name: configure
        run: |
          perl Makefile.PL
      - name: build
        run: |
            make -j2
      - name: test
        run: |
            make test
      - name: artifacts
        uses: actions/upload-artifact@v7
        with:
          name: logs-${{ matrix.LIBHEIF_RELEASE }}
          path: testout/
          retention-days: 7
